#!/usr/bin/env bash

command="${1}"
timeout="${2:-30}"

timeout "${timeout}" bash -c "until ${command}; do sleep 1; done" \
|| (
    >&2 printf "command was never successful, aborting due to %s s timeout!\n" "${timeout}"
    exit 1
)
